global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["192.168.53.200:9090"]
  - job_name: "node1"
    static_configs:
      - targets: ["192.168.53.201:9100"]
  - job_name: "node2"
    static_configs:
      - targets: ["192.168.53.202:9100"]
      
